# Generated by Django 5.0.3 on 2024-03-18 11:32

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('contact', models.BigIntegerField()),
                ('subject', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=100)),
                ('comment', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'Enquiry',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
